# WEATHER PREDICTION

### IMPORTING REQUIRED PACKAGES

In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### LOADING DATA FROM DATA SOURCE

In [15]:
df = pd.read_csv("pune.csv")
df

,date_time,maxtempC,mintempC,sunHour,uvIndex,moon_illumination,moonrise,moonset,sunrise,sunset,...,WindChillC,WindGustKmph,cloudcover,humidity,precipMM,pressure,tempC,visibility,winddirDegree,windspeedKmph
0,2013-01-01 00:00:00,32,20,11.0,6,68,09:38 PM,09:37 AM,07:07 AM,06:09 PM,...,21,13,31,69,0.0,1010,21,10,274,6
1,2013-01-01 01:00:00,32,20,11.0,6,68,09:38 PM,09:37 AM,07:07 AM,06:09 PM,...,20,12,31,71,0.0,1011,20,10,271,6
2,2013-01-01 02:00:00,32,20,11.0,6,68,09:38 PM,09:37 AM,07:07 AM,06:09 PM,...,20,11,31,73,0.0,1011,20,10,267,6
3,2013-01-01 03:00:00,32,20,11.0,6,68,09:38 PM,09:37 AM,07:07 AM,06:09 PM,...,20,10,31,75,0.0,1011,20,10,264,5
4,2013-01-01 04:00:00,32,20,11.0,6,68,09:38 PM,09:37 AM,07:07 AM,06:09 PM,...,21,8,33,71,0.0,1012,21,10,261,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80563,2022-03-11 19:00:00,35,23,11.8,7,56,12:40 PM,01:33 AM,06:46 AM,06:43 PM,...,30,10,6,28,0.0,1009,30,10,235,7
80564,2022-03-11 20:00:00,35,23,11.8,7,56,12:40 PM,01:33 AM,06:46 AM,06:43 PM,...,29,14,7,29,0.0,1010,29,10,289,9
80565,2022-03-11 21:00:00,35,23,11.8,7,56,12:40 PM,01:33 AM,06:46 AM,06:43 PM,...,27,12,9,30,0.0,1012,27,10,343,12
80566,2022-03-11 22:00:00,35,23,11.8,7,56,12:40 PM,01:33 AM,06:46 AM,06:43 PM,...,26,14,8,31,0.0,1011,26,10,234,11
80567,2022-03-11 23:00:00,35,23,11.8,7,56,12:40 PM,01:33 AM,06:46 AM,06:43 PM,...,25,15,7,32,0.0,1011,25,10,125,10

## EXPLORATORY DATA ANALYSIS (EDA)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80568 entries, 0 to 80567
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date_time          80568 non-null  object
 1   maxtempC           80568 non-null  int64
 2   mintempC           80568 non-null  int64
 3   sunHour            80568 non-null  float64
 4   uvIndex            80568 non-null  int64
 5   moon_illumination  80568 non-null  int64
 6   moonrise           80568 non-null  object
 7   moonset            80568 non-null  object
 8   sunrise            80568 non-null  object
 9   sunset             80568 non-null  object
 10  DewPointC          80568 non-null  int64
 11  FeelsLikeC         80568 non-null  int64
 12  HeatIndexC         80568 non-null  int64
 13  WindChillC         80568 non-null  int64
 14  WindGustKmph       80568 non-null  int64
 15  cloudcover         80568 non-null  int64
 16  humidity           80568 non-null  int64
 17  precipMM           80536 non-null  float64
 18  pressure           80568 non-null  int64
 19  tempC              80568 non-null  int64
 20  visibility         80568 non-null  int64
 21  winddirDegree      80568 non-null  int64
 22  windspeedKmph      80568 non-null  int64
dtypes: float64(2), int64(16), object(5)
memory usage: 14.1+ MB

In [17]:
df.describe()

,maxtempC,mintempC,sunHour,uvIndex,moon_illumination,DewPointC,FeelsLikeC,HeatIndexC,WindChillC,WindGustKmph,cloudcover,humidity,precipMM,pressure,tempC,visibility,winddirDegree,windspeedKmph
count,80568.000000,80568.000000,80568.000000,80568.000000,80568.000000,80568.000000,80568.000000,80568.000000,80568.000000,80568.000000,80568.000000,80568.000000,80536.000000,80568.000000,80568.000000,80568.000000,80568.000000,80568.000000
mean,30.996425,21.079833,11.131010,6.238010,46.014298,15.104930,26.221142,26.405819,25.353974,17.804699,31.087938,56.836424,0.233530,1009.907283,25.354434,9.498523,206.805208,9.944680
std,4.269333,2.718931,0.995869,0.922829,31.247205,5.966829,4.482248,4.333984,4.630465,8.318761,33.636361,24.633249,0.817405,3.583082,4.629282,1.413985,89.666001,4.891564
min,21.000000,11.000000,8.300000,4.000000,0.000000,-9.000000,10.000000,11.000000,10.000000,1.000000,0.000000,4.000000,0.000000,997.000000,11.000000,0.000000,0.000000,0.000000
25%,28.000000,19.000000,10.500000,6.000000,18.000000,10.000000,25.000000,25.000000,22.000000,12.000000,3.000000,36.000000,0.000000,1007.000000,22.000000,10.000000,107.000000,6.000000
50%,30.000000,21.000000,11.000000,6.000000,46.000000,16.000000,26.000000,26.000000,25.000000,16.000000,12.000000,57.000000,0.000000,1010.000000,25.000000,10.000000,253.000000,9.000000
75%,34.000000,23.000000,11.900000,7.000000,73.000000,21.000000,29.000000,29.000000,28.000000,23.000000,65.000000,80.000000,0.100000,1013.000000,28.000000,10.000000,274.000000,13.000000
max,43.000000,28.000000,13.500000,8.000000,100.000000,24.000000,44.000000,44.000000,43.000000,76.000000,100.000000,98.000000,25.700000,1021.000000,43.000000,10.000000,360.000000,40.000000

## DATA PREPROCESSING

### Scaling

In [18]:
df.drop(['date_time', 'moonrise', 'moonset', 'sunrise', 'sunset'], axis=1, inplace=True)

In [19]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

scaler.fit(df)
scaled_df=scaler.transform(df)

In [20]:
new_df = pd.DataFrame(scaled_df,columns=df.columns)

In [21]:
print(new_df)

       maxtempC  mintempC   sunHour   uvIndex  moon_illumination  DewPointC  \
0      0.235067 -0.397156 -0.131554 -0.257915           0.703610  -0.017586
1      0.235067 -0.397156 -0.131554 -0.257915           0.703610  -0.017586
2      0.235067 -0.397156 -0.131554 -0.257915           0.703610  -0.017586
3      0.235067 -0.397156 -0.131554 -0.257915           0.703610  -0.017586
4      0.235067 -0.397156 -0.131554 -0.257915           0.703610   0.150009
...         ...       ...       ...       ...                ...        ...
80563  0.937758  0.706226  0.671769  0.825716           0.319573  -1.023151
80564  0.937758  0.706226  0.671769  0.825716           0.319573  -1.023151
80565  0.937758  0.706226  0.671769  0.825716           0.319573  -0.687963
80566  0.937758  0.706226  0.671769  0.825716           0.319573  -0.687963
80567  0.937758  0.706226  0.671769  0.825716           0.319573  -0.687963

       FeelsLikeC  HeatIndexC  WindChillC  WindGustKmph  cloudcover  humidity  \
0       -1.164856   -1.247317   -0.940295     -0.577577   -0.002614  0.493790
1       -1.387960   -1.478053   -1.156257     -0.697788   -0.002614  0.574982
2       -1.387960   -1.478053   -1.156257     -0.817999   -0.002614  0.656173
3       -1.387960   -1.478053   -1.156257     -0.938210   -0.002614  0.737365
4       -1.164856   -0.555109   -0.940295     -1.178632    0.056845  0.574982
...           ...         ...         ...           ...         ...       ...
80563    0.396870    0.367835    1.003367     -0.938210   -0.745862 -1.170637
80564    0.396870    0.367835    0.787404     -0.457367   -0.716132 -1.130042
80565   -0.049338   -0.093637    0.355480     -0.697788   -0.656673 -1.089446
80566   -0.049338   -0.093637    0.139517     -0.457367   -0.686402 -1.048850
80567   -0.272441   -0.324373   -0.076445     -0.337156   -0.716132 -1.008254

       precipMM  pressure     tempC  visibility  winddirDegree  windspeedKmph
0     -0.285699  0.025876 -0.940634    0.354657       0.749395      -0.806430
1     -0.285699  0.304968 -1.156652    0.354657       0.715937      -0.806430
2     -0.285699  0.304968 -1.156652    0.354657       0.671327      -0.806430
3     -0.285699  0.304968 -1.156652    0.354657       0.637869      -1.010865
4     -0.285699  0.584059 -0.940634    0.354657       0.604411      -1.010865
...         ...       ...       ...         ...            ...            ...
80563 -0.285699 -0.253215  1.003524    0.354657       0.314444      -0.601995
80564 -0.285699  0.025876  0.787506    0.354657       0.916683      -0.193126
80565 -0.285699  0.584059  0.355471    0.354657       1.518922       0.420179
80566 -0.285699  0.304968  0.139454    0.354657       0.303292       0.215744
80567 -0.285699  0.304968 -0.076564    0.354657      -0.912338       0.011309

[80568 rows x 18 columns]

In [22]:
new_df.isna().sum()

maxtempC              0
mintempC              0
sunHour               0
uvIndex               0
moon_illumination     0
DewPointC             0
FeelsLikeC            0
HeatIndexC            0
WindChillC            0
WindGustKmph          0
cloudcover            0
humidity              0
precipMM             32
pressure              0
tempC                 0
visibility            0
winddirDegree         0
windspeedKmph         0
dtype: int64